openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test Service
servers:
  - url: api/test
paths:
  /getPeople:
    get:
      summary: GetPeople
      operationId: getPeople
      tags:
        -  getPeople
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
  /getPerson/{personname}:
    get:
      summary: Get Person
      operationId: getPerson
      tags:
        -  getPerson
      parameters:
        - $ref: "#/components/parameters/personname"
      responses:
        200:
          description: Schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'                
components:
  parameters:
    personname:
      name: personname
      in: path
      required: true
      description: a Name of a Person
      schema:
        type: string
  schemas:
    People:
      type: array
      items:
        $ref: '#/components/schemas/Person'
    Person:
      required:
        - name
      properties:
        name:
          type: string