server:
  port: 8081
spring:
  application:
    name: jenkinstest
  datasource:
    url: jdbc:postgresql://localhost:39000/lernplattform
    username: testuser
    password: testpw
    driver-class-name: org.postgresql.Driver   
